myFunction RETURNS INT IS *,
anotherFunction RETURNS FLOAT WITH x AS INT IS *,
sum RETURNS INT WITH a AS INT,
b AS INT IS *,
declare x AS INT,
declare y AS FLOAT WITH 3.14,
x IS 10,
y IS 5.5,
callFunction(),
calculate(42),
addNumbers(1,
2,
3),
RETURN x AS INT;
